# Generated by Django 5.1.3 on 2025-02-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
